Machine learning analysis for the preprocessed absenteeism data

In [1]:
import pandas as pd
import numpy as np

df_prep = pd.read_csv("Resources\Absenteeism_preprocessed_data.csv")

In [2]:
df_prep.head()

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0           0         0         0         0         1      7                1   
1           1         0         0         0         0      7                1   
2           2         0         0         0         1      7                2   
3           3         1         0         0         0      7                3   
4           4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [3]:
df_prep['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(df_prep['Absenteeism Time in Hours'] > df_prep['Absenteeism Time in Hours'].median(), 1, 0)

In [5]:
print(len(targets))
sum(targets)

700


319

In [6]:
df = df_prep.drop(['Absenteeism Time in Hours'], axis = 1)

In [7]:
df['Excessive Absenteeism'] = targets
df.head()

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0           0         0         0         0         1      7                1   
1           1         0         0         0         0      7                1   
2           2         0         0         0         1      7                2   
3           3         1         0         0         0      7                3   
4           4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [8]:
df = df.drop(['Unnamed: 0'], axis = 1)

In [9]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [10]:
df_with_targets = df.copy()

In [11]:
df_with_targets.shape

(700, 15)

In [12]:
unscaled_inputs = df_with_targets.iloc[:,:-1]

In [13]:
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

### Standardization

In [14]:
from sklearn.preprocessing import StandardScaler
absenteism_scaler = StandardScaler()

In [15]:
absenteism_scaler.fit(unscaled_inputs)

C:\Users\Karolina\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
scaled_inputs = absenteism_scaler.transform(unscaled_inputs)

C:\Users\Karolina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [17]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state=42, shuffle = True)

C:\Users\Karolina\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [21]:
len(X_train)

560

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [23]:
reg = LogisticRegression()

In [25]:
reg.fit(X_train, y_train)

C:\Users\Karolina\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
reg.score(X_train, y_train)

0.7732142857142857

In [28]:
predictions = reg.predict(X_test)

In [30]:
reg.score(X_test, y_test)

0.7571428571428571

In [31]:
predictions == y_test

array([False, False, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True, False,
        True, False, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
        True, False,  True, False,  True,  True, False, False, False,
        True, False,

In [32]:
np.sum(predictions==y_test)

106

In [34]:
accuracy = np.sum(predictions==y_test) / len(predictions)
accuracy

0.7571428571428571

In [36]:
reg.intercept_

array([-0.17869474])

In [37]:
reg.coef_

array([[ 2.13760855,  0.34685155,  1.537381  ,  1.41116497,  0.09469695,
        -0.15167141,  0.79485964, -0.09792415, -0.28721165, -0.01117007,
         0.28412025, -0.14755158,  0.42284937, -0.36515323]])

In [38]:
feature_names = unscaled_inputs.columns.values

In [39]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_names)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficients
0                  Reason_1      2.137609
1                  Reason_2      0.346852
2                  Reason_3      1.537381
3                  Reason_4      1.411165
4                     Month      0.094697
5           Day of the week     -0.151671
6    Transportation Expense      0.794860
7          Distance to Work     -0.097924
8                       Age     -0.287212
9   Daily Work Load Average     -0.011170
10          Body Mass Index      0.284120
11                Education     -0.147552
12                 Children      0.422849
13                     Pets     -0.365153

In [41]:
unscaled_inputs.corr()

Reason_1  Reason_2  Reason_3  Reason_4     Month  \
Reason_1                 1.000000 -0.053683 -0.181568 -0.702915 -0.002826   
Reason_2                -0.053683  1.000000 -0.029241 -0.113203 -0.018406   
Reason_3                -0.181568 -0.029241  1.000000 -0.382881 -0.013796   
Reason_4                -0.702915 -0.113203 -0.382881  1.000000 -0.036989   
Month                   -0.002826 -0.018406 -0.013796 -0.036989  1.000000   
Day of the week         -0.078055 -0.011194 -0.103661  0.110696  0.071718   
Transportation Expense   0.008725 -0.000487  0.016658 -0.066727  0.135803   
Distance to Work        -0.098625 -0.022372 -0.023367  0.130687 -0.003970   
Age                      0.022772  0.030381 -0.019797 -0.062765  0.004983   
Daily Work Load Average  0.165434 -0.016664  0.014542 -0.163826 -0.174029   
Body Mass Index         -0.077597 -0.078084 -0.038087  0.071160  0.058254   
Education                0.095056  0.124487  0.046426 -0.108243 -0.075561   
Children                -0.061594  0.081867  0.088256 -0.049680  0.082057   
Pets                    -0.054502 -0.041531  0.105854 -0.013062  0.076250   

                         Day of the week  Transportation Expense  \
Reason_1                       -0.078055                0.008725   
Reason_2                       -0.011194               -0.000487   
Reason_3                       -0.103661                0.016658   
Reason_4                        0.110696               -0.066727   
Month                           0.071718                0.135803   
Day of the week                 1.000000                0.048516   
Transportation Expense          0.048516                1.000000   
Distance to Work                0.089484                0.234940   
Age                             0.004039               -0.223828   
Daily Work Load Average         0.012573                0.006123   
Body Mass Index                -0.071750               -0.140531   
Education                       0.037951               -0.019623   
Children                        0.111936                0.381749   
Pets                           -0.045163                0.446887   

                         Distance to Work       Age  Daily Work Load Average  \
Reason_1                        -0.098625  0.022772                 0.165434   
Reason_2                        -0.022372  0.030381                -0.016664   
Reason_3                        -0.023367 -0.019797                 0.014542   
Reason_4                         0.130687 -0.062765                -0.163826   
Month                           -0.003970  0.004983                -0.174029   
Day of the week                  0.089484  0.004039                 0.012573   
Transportation Expense           0.234940 -0.223828                 0.006123   
Distance to Work                 1.000000 -0.131076                -0.073683   
Age                             -0.131076  1.000000                -0.045452   
Daily Work Load Average         -0.073683 -0.045452                 1.000000   
Body Mass Index                  0.136190  0.483762                -0.098430   
Education                       -0.289994 -0.219723                -0.058990   
Children                         0.048534  0.046930                 0.032194   
Pets                             0.171585 -0.252067                 0.010490   

                         Body Mass Index  Education  Children      Pets  
Reason_1                       -0.077597   0.095056 -0.061594 -0.054502  
Reason_2                       -0.078084   0.124487  0.081867 -0.041531  
Reason_3                       -0.038087   0.046426  0.088256  0.105854  
Reason_4                        0.071160  -0.108243 -0.049680 -0.013062  
Month                           0.058254  -0.075561  0.082057  0.076250  
Day of the week                -0.071750   0.037951  0.111936 -0.045163  
Transportation Expense         -0.140531  -0.019623  0.381749  0.446887  
Distance to Work                0.136190  -0.289994  0.

In [42]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table

In [44]:
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficients
0                 Intercept     -0.178695
1                  Reason_1      2.137609
2                  Reason_2      0.346852
3                  Reason_3      1.537381
4                  Reason_4      1.411165
5                     Month      0.094697
6           Day of the week     -0.151671
7    Transportation Expense      0.794860
8          Distance to Work     -0.097924
9                       Age     -0.287212
10  Daily Work Load Average     -0.011170
11          Body Mass Index      0.284120
12                Education     -0.147552
13                 Children      0.422849
14                     Pets     -0.365153